// PATH: eslint.config.js
// ESLint v9 flat config — enforces layer boundary rules via eslint-plugin-boundaries
// Plugin docs: https://github.com/javierbrea/eslint-plugin-boundaries

import boundaries from 'eslint-plugin-boundaries'
import pluginQuery from '@tanstack/eslint-plugin-query'
import js from '@eslint/js'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import globals from 'globals'
import tseslint from 'typescript-eslint'

export default tseslint.config(
  // ─── Global ignores ───────────────────────────────────────────────────────
  {
    ignores: [
      'dist/**',
      'node_modules/**',
      // Auto-generated by TanStack Router — never lint this file
      'src/routeTree.gen.ts',
    ],
  },

  // ─── Base rules ───────────────────────────────────────────────────────────
  js.configs.recommended,
  ...tseslint.configs.recommended,
  ...pluginQuery.configs['flat/recommended'],

  {
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      ecmaVersion: 2022,
      globals: globals.browser,
      parserOptions: {
        // Enable type-aware linting for stronger checks
        project: ['./tsconfig.app.json', './tsconfig.node.json'],
        tsconfigRootDir: import.meta.dirname,
      },
    },
    plugins: {
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
      boundaries,
    },
    settings: {
      // ─── Layer element definitions for eslint-plugin-boundaries ──────────
      'boundaries/elements': [
        { type: 'types', pattern: 'src/types/*' },
        { type: 'config', pattern: 'src/config/*' },
        { type: 'lib', pattern: 'src/lib/**/*' },
        { type: 'hooks', pattern: 'src/hooks/*' },
        { type: 'stores', pattern: 'src/stores/*' },
        { type: 'assets', pattern: 'src/assets/**/*' },
        { type: 'styles', pattern: 'src/styles/*' },
        { type: 'services', pattern: 'src/services/**/*' },
        { type: 'components', pattern: 'src/components/**/*' },
        { type: 'features', pattern: 'src/features/*/*', capture: ['feature'] },
        { type: 'layouts', pattern: 'src/layouts/**/*' },
        { type: 'app', pattern: 'src/app/**/*' },
        { type: 'routes', pattern: 'src/routes/**/*' },
      ],
      // Allow resolving TypeScript path aliases in boundaries plugin
      'import/resolver': {
        typescript: { alwaysTryTypes: true },
      },
    },
    rules: {
      // ─── React Hooks ──────────────────────────────────────────────────────
      ...reactHooks.configs.recommended.rules,
      'react-refresh/only-export-components': ['warn', { allowConstantExport: true }],

      // ─── TypeScript ───────────────────────────────────────────────────────
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/consistent-type-imports': 'error',
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],

      // ─── Boundary Rules (import direction enforcement) ────────────────────
      // types: cannot import anything
      'boundaries/element-types': [
        'error',
        {
          default: 'disallow',
          rules: [
            // types: no imports
            { from: 'types', allow: [] },
            // config: can only import types
            { from: 'config', allow: ['types'] },
            // lib: can only import types
            { from: 'lib', allow: ['types'] },
            // hooks: can import types + config
            { from: 'hooks', allow: ['types', 'config'] },
            // stores (global): can import types + config
            { from: 'stores', allow: ['types', 'config'] },
            // services: can import config + types
            { from: 'services', allow: ['config', 'types'] },
            // components: can import lib/utils, types, assets
            { from: 'components', allow: ['lib', 'types', 'assets', 'styles'] },
            {
              from: 'features',
              allow: [
                'lib',
                'config',
                'hooks',
                'components',
                'types',
                'assets',
                // Allow a feature to import from its own internal directories:
                // `features` is the generic type, capturing the sub-folder name in `feature`
                ['features', { feature: '${from.feature}' }],
              ],
            },
            // layouts: can import components, stores, hooks, lib
            {
              from: 'layouts',
              allow: ['components', 'stores', 'hooks', 'lib', 'types', 'assets'],
            },
            // app: can import everything except routes
            {
              from: 'app',
              allow: ['components', 'config', 'lib', 'stores', 'types'],
            },
            // routes: can import features (index only), layouts, stores, config
            {
              from: 'routes',
              allow: ['features', 'layouts', 'stores', 'config', 'components', 'types', 'lib'],
            },
          ],
        },
      ],
    },
  },
)
