// PATH: src/main.tsx
// Application entry point.
// Creates the TanStack Router with context (queryClient + auth)
// and renders RouterProvider inside StrictMode.

import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { createRouter, RouterProvider } from '@tanstack/react-router'

import { queryClient } from '@/config/queryClient'
import { useAuthStore } from '@/features/auth/stores/auth.store'
import { NotFoundPage } from '@/routes/errors/404'
import { ErrorFallback } from '@/shared/ui/common/ErrorBoundary/ErrorFallback'

// Import the auto-generated route tree — DO NOT edit this file manually
import { routeTree } from './routeTree.gen'

// Import global styles — must be imported here, not in any component
import './styles/globals.scss'
import './styles/globals-admin.scss'
import './styles/globals-main.scss'

// ─── Create Router ─────────────────────────────────────────────────────────────
/**
 * Router context is available in all routes via useRouteContext().
 * - queryClient: for loader functions to call ensureQueryData
 * - auth: for reading auth state in beforeLoad guards
 */
const router = createRouter({
  routeTree,
  // Default pending milliseconds — avoids flash of loading state for fast navigations
  defaultPreloadStaleTime: 0,
  // Global 404 component
  defaultNotFoundComponent: () => <NotFoundPage />,
  // Global error component — catches errors that bubble up past the root route
  defaultErrorComponent: ({ error }) => (
    <ErrorFallback error={error instanceof Error ? error : new Error(String(error))} />
  ),
  context: {
    queryClient,
    // We read the current auth state at router creation time.
    // Route guards access up-to-date state via useAuthStore.getState() in beforeLoad.
    auth: useAuthStore.getState(),
  },
})

// ─── Type augmentation for TypeScript ─────────────────────────────────────────
// This tells TypeScript about our custom router instance globally
declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router
  }
}

// ─── Mount ─────────────────────────────────────────────────────────────────────
const rootElement = document.getElementById('root')
if (!rootElement) {
  throw new Error('Root element #root not found in index.html')
}

createRoot(rootElement).render(
  <StrictMode>
    <RouterProvider router={router} />
  </StrictMode>,
)
